name: dotnet-hello
base: core20
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: This is a sample .NET application.
description: |
  This is a sample .NET application.

grade: devel
confinement: strict

parts:
  dotnet-hello:
    #build-snaps: [dotnet-sdk]
    source: .
    plugin: nil
    override-build: |
      dotnet="/snap/bin/dotnet-sdk.dotnet"
      $dotnet publish --self-contained -r linux-x64 -c Release -o "${SNAPCRAFT_PART_INSTALL}"
    stage-packages:
      - libicu66
      - libssl1.1
      - libcurl4
      - libgssapi-krb5-2
      - libstdc++6
      - zlib1g
      - libgcc1
      - libtinfo5
      - liblttng-ust0
      - liburcu6


apps:
  dotnet-hello:
    command: dotnet-hello
    environment:
      DOTNET_ROOT: $SNAP  # Not required?
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    plugs:
      - process-control
